name: backend server build
on:
  workflow_dispatch:
    inputs:
      dir:
        required: true
        description: DockerFile Dir
      tag:
        required: true
        description: "docker version to release"
    
env:
  REGISTRY: ghcr.io
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GithubPackages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{github.event.inputs.dir}}    
          push: true        
          cache-from: type=gha
          cache-to: type=gha,mode=max                
          tags: "${{env.REGISTRY}}/timzaak/${{github.event.inputs.tag}}"