name: docker release
# Docker registry is defined by secrets
on:
  workflow_dispatch:
    inputs:
      docker_file:
        required: true
        description: DockerFile Path
      tag:
        required: true
        description: Docker Image Name with Tag

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          allow: security.insecure
          tags: ${{secrets.DOCKER_REGISTRY}}/${{github.event.inputs.tag}}
          file: ${{github.event.inputs.docker_file}}



