name: docker transfer
# Docker registry is defined by secrets
on:
  workflow_dispatch:
    inputs:
      source_image:
        required: true
        description: source docker image, like ghrc.io/fornetcode/spa-server:latest
      target_image:
        required: true
        description: docker image name with tag, like fornetcode/spa-server:latest

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: docker pull
        run: docker pull ${{github.event.inputs.source_image}}
      - name: docker tag and push
        run: > 
          docker tag ${{github.event.inputs.source_image}} ${{secrets.DOCKER_REGISTRY}}/${{github.event.inputs.target_image}} &&  \
          docker push ${{secrets.DOCKER_REGISTRY}}/${{github.event.inputs.target_image}}"

